# Generated by Django 2.2.4 on 2019-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_title', models.TextField(max_length=250)),
                ('count_data', models.DateTimeField()),
                ('count_group', models.TextField(max_length=250)),
                ('count_subgroup', models.TextField(max_length=250)),
                ('count_summa', models.IntegerField()),
            ],
        ),
    ]
