# Generated by Django 2.2.4 on 2019-08-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190812_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accountant_record',
            new_name='AccountantRecord',
        ),
    ]
