# Generated by Django 2.2.4 on 2019-08-12 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190812_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountantrecord',
            old_name='count_summa',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='accountantrecord',
            old_name='count_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='accountantrecord',
            old_name='count_subgroup',
            new_name='subgroup',
        ),
        migrations.RenameField(
            model_name='accountantrecord',
            old_name='count_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='accountantrecord',
            name='count_data',
        ),
        migrations.AddField(
            model_name='accountantrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountantrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
