# Generated by Django 2.2.4 on 2019-08-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190812_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountantrecord',
            name='title',
        ),
    ]
